export const knockoutMatches = [
    { matchId: "match073", phase: "ROUND_OF_32", homeSlot: "2A", awaySlot: "2B" },
    { matchId: "match074", phase: "ROUND_OF_32", homeSlot: "1C", awaySlot: "2F" },
    { matchId: "match075", phase: "ROUND_OF_32", homeSlot: "1E", awaySlot: "3ABCDF" },
    { matchId: "match076", phase: "ROUND_OF_32", homeSlot: "1F", awaySlot: "2C" },
    { matchId: "match077", phase: "ROUND_OF_32", homeSlot: "2E", awaySlot: "2I" },
    { matchId: "match078", phase: "ROUND_OF_32", homeSlot: "1I", awaySlot: "3CDFGH" },
    { matchId: "match079", phase: "ROUND_OF_32", homeSlot: "1A", awaySlot: "3CEFHI" },
    { matchId: "match080", phase: "ROUND_OF_32", homeSlot: "1L", awaySlot: "3EHIJK" },
    { matchId: "match081", phase: "ROUND_OF_32", homeSlot: "1G", awaySlot: "3AEHIJ" },
    { matchId: "match082", phase: "ROUND_OF_32", homeSlot: "1D", awaySlot: "3BEFIJ" },
    { matchId: "match083", phase: "ROUND_OF_32", homeSlot: "1H", awaySlot: "2J" },
    { matchId: "match084", phase: "ROUND_OF_32", homeSlot: "2K", awaySlot: "2L" },
    { matchId: "match085", phase: "ROUND_OF_32", homeSlot: "1B", awaySlot: "3EFGIJ" },
    { matchId: "match086", phase: "ROUND_OF_32", homeSlot: "2D", awaySlot: "2G" },
    { matchId: "match087", phase: "ROUND_OF_32", homeSlot: "1J", awaySlot: "2H" },
    { matchId: "match088", phase: "ROUND_OF_32", homeSlot: "1K", awaySlot: "3DEIJL" },
    { matchId: "match089", phase: "ROUND_OF_16", homeSlot: "W73", awaySlot: "W75" },
    { matchId: "match090", phase: "ROUND_OF_16", homeSlot: "W74", awaySlot: "W77" },
    { matchId: "match091", phase: "ROUND_OF_16", homeSlot: "W76", awaySlot: "W78" },
    { matchId: "match092", phase: "ROUND_OF_16", homeSlot: "W79", awaySlot: "W80" },
    { matchId: "match093", phase: "ROUND_OF_16", homeSlot: "W83", awaySlot: "W84" },
    { matchId: "match094", phase: "ROUND_OF_16", homeSlot: "W81", awaySlot: "W82" },
    { matchId: "match095", phase: "ROUND_OF_16", homeSlot: "W86", awaySlot: "W88" },
    { matchId: "match096", phase: "ROUND_OF_16", homeSlot: "W85", awaySlot: "W87" },
    { matchId: "match097", phase: "QUARTERFINAL", homeSlot: "W89", awaySlot: "W90" },
    { matchId: "match098", phase: "QUARTERFINAL", homeSlot: "W93", awaySlot: "W94" },
    { matchId: "match099", phase: "QUARTERFINAL", homeSlot: "W91", awaySlot: "W92" },
    { matchId: "match100", phase: "QUARTERFINAL", homeSlot: "W95", awaySlot: "W96" },
    { matchId: "match101", phase: "SEMIFINAL", homeSlot: "W97", awaySlot: "W98" },
    { matchId: "match102", phase: "SEMIFINAL", homeSlot: "W99", awaySlot: "W100" },
    { matchId: "match103", phase: "THIRD_PLACE", homeSlot: "L101", awaySlot: "L102" },
    { matchId: "match104", phase: "FINAL", homeSlot: "W101", awaySlot: "W102" }

];